apiVersion: v1
kind: Pod
metadata:
  name: runas
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  volumes:
  - name: mydisk
    emptyDir: {}
  containers:
  - name: runas
    image: andrewahn2134/security-context:v1
    imagePullPolicy: Always
    volumeMounts:
    - name: mydisk
      mountPath: /mydisk
    ports:
    - containerPort: 8080
